- name: Install zsh
  pacman: name=zsh
  tags:
    - zsh
- name: Change shell
  shell: chsh -s `which zsh`
  tags:
    - zsh
- name: Install oh-my-zsh
  shell: sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
  tags:
    - zsh
- name: Install zsh autosuggestions
  ansible.builtin.git:
    repo: "https://github.com/zsh-users/zsh-autosuggestions"
    dest: "~/.oh-my-zsh/plugins/zsh-autosuggestions"
  tags:
    - zsh
- name: Update zshrc
  shell: sed -i 's/(git/(git zsh-autosuggestions/' ~/.zshrc
  tags:
    - zsh
